### ISSUE TITLE
搜索建议无法显示

### ISSUE THREAD

**Issue by y3342113181** [Nitai9h/nitaipage#2]
最新版插件搜索建议无法显示

**Comment by Nitai9h** [comment]
已解决

**Comment by sugu666** [comment]
edge插件多久更新呢？

**Comment by Nitai9h** [comment]
微软那边审核要等七天

**Comment by y3342113181** [comment]
好的

**Comment by y3342113181** [comment]
![image](https://github.com/user-attachments/assets/39bfdb0c-9d78-47fe-8aee-c9a47cc58084)
yi'jiu'wu'fa'xian's依旧无法显示搜索建议
![image](https://github.com/user-attachments/assets/e6d31ae0-130d-4ac7-ab6d-2710086821fd)
另外起始页图标显示异常

**Comment by Nitai9h** [comment]
我这里可以正常使用，你可以用你的浏览器访问[https://suggestion.baidu.com/su?wd=test](https://suggestion.baidu.com/su?wd=test)
检查浏览器报错并尝试解决。

这周的更新将可以自由选择搜索建议
图标这周也会一并修复

**Comment by y3342113181** [comment]
是edge插件有问题，网址没问题

**Comment by Nitai9h** [comment]
[在线版](https://www.nitai.us.kg/)可以正常显示搜索建议？

**Comment by y3342113181** [comment]
是的

**Comment by y3342113181** [comment]
包括图标也是正常的，就是插件有点问题

**Comment by Nitai9h** [comment]
打开开发者工具（F12）看看控制台有没有报错

**Comment by y3342113181** [comment]
![image](https://github.com/user-attachments/assets/72e21825-1aa6-4d3a-a995-551cf7bbefe9)
有报错

**Comment by Nitai9h** [comment]
这周修复

**Comment by y3342113181** [comment]
![image](https://github.com/user-attachments/assets/5b337904-df4f-4980-a831-9cb77550d2c3)
还是浏览器插件问题，搜索建议的问题

**Comment by y3342113181** [comment]
![image](https://github.com/user-attachments/assets/fe283407-ecb5-404a-ac13-dc0ab4accb33)

**Comment by Nitai9h** [comment]
打开edge商店，重新下载最新版

**Comment by y3342113181** [comment]
就是最新的，12月8号更新的版本

**Comment by Nitai9h** [comment]
打开扩展页面的开发者模式，确保在扩展页面的扩展名旁显示的版本为1.2.14.3，而不是1.2.14.2
![Screenshot_20241213_221942](https://github.com/user-attachments/assets/a3973b8c-cebb-4237-9862-9d8b43a3170c)

**Comment by y3342113181** [comment]
1.2.14.2是最新的edge插件版本号，在插件商店是1.2.14.3


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nitai9h/nitaipage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月13日(星期五) 晚上10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nitai9h/nitaipage] 搜索建议无法显示 (Issue #2)





 
打开扩展页面的开发者模式，确保在扩展页面的扩展名旁显示的版本为1.2.14.3，而不是1.2.14.2
 Screenshot_20241213_221942.jpg (view on web)

**Comment by Nitai9h** [comment]
edge商店的1.2.14.3是改了权限后的，但实际上还是1.2.14.2。最好先移除扩展再重新安装

**Comment by y3342113181** [comment]
已经是移除之后重新安装的样子了





------------------ 原始邮件 ------------------
发件人: Nitai ***@***.***&gt;
发送时间: 2024年12月16日 12:21
收件人: 3342113181 ***@***.***&gt;
主题: Re: [Nitai9h/nitaipage] 搜索建议无法显示 (Issue #2)





 
edge商店的1.2.14.3是改了权限后的，但实际上还是1.2.14.2。最好先移除扩展再重新安装

**Comment by Nitai9h** [comment]
看看你这里是不是 安全的来源，不是的话就是浏览器拦截了。
我的edge是可以正常使用的
![Screenshot_20241216_124823_edit_49479460653831](https://github.com/user-attachments/assets/7cd38ce0-fe8f-424a-97e8-343dfcf42eda)

**Comment by y3342113181** [comment]
这样的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nitai9h/nitaipage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月16日(星期一) 中午12:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nitai9h/nitaipage] 搜索建议无法显示 (Issue #2)





 
看看你这里是不是 安全的来源，不是的话就是浏览器拦截了。
 我的edge是可以正常使用的
 Screenshot_20241216_124823_edit_49479460653831.jpg (view on web)

**Comment by Nitai9h** [comment]
邮件回复看不到图片

**Comment by y3342113181** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
应该可以看到了

**Comment by y3342113181** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
应该可以看到了

**Comment by y3342113181** [comment]
![image](https://github.com/user-attachments/assets/f08516a2-dd69-4440-9ede-8328f45e0133)
![image](https://github.com/user-attachments/assets/3b0be2bd-9532-4819-b4b3-5c2572a483e3)
应该可以看到了

**Comment by Nitai9h** [comment]
只要保证插件页面写的是1.2.14.3就行了，edge商店的这个版本后台就是1.2.14.2
